# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q1oCleYI6T-gixJUmkt0YbhUSIK00hDF
"""

import datetime
import streamlit as st

kyou = datetime.datetime.today()
d = st.date_input('出荷日を入力してください。')
st.write('出荷日：', d)
